#!/bin/bash
set -euo pipefail

# git-hooks-install.sh — Install a pre-commit hook for this repo.
# The hook runs:
#   1) bash -n on every staged *.sh file
#   2) scripts/plugin-validate.sh if any plugin file is staged
#   3) bash tests/test-portability.sh (fast, no external calls) if it exists
#
# Usage:
#   bash scripts/git-hooks-install.sh             # install (refuses to overwrite)
#   bash scripts/git-hooks-install.sh --force     # overwrite an existing hook
#   bash scripts/git-hooks-install.sh --uninstall # remove the hook
#   bash scripts/git-hooks-install.sh --status    # show current hook contents

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_PATH="$SCRIPT_DIR/.git/hooks/pre-commit"

FORCE=0
UNINSTALL=0
STATUS=0

while [ $# -gt 0 ]; do
  case "$1" in
    --force)     FORCE=1; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --status)    STATUS=1; shift ;;
    -h|--help)
      sed -n '4,13p' "$0" | sed 's/^# *//'
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

if [ -t 1 ]; then
  G='\033[32m'; R='\033[31m'; Y='\033[33m'; D='\033[90m'; B='\033[1m'; Z='\033[0m'
else
  G=''; R=''; Y=''; D=''; B=''; Z=''
fi

[ -d "$SCRIPT_DIR/.git" ] || {
  echo "ERROR: not a git working tree at $SCRIPT_DIR" >&2; exit 1; }

if [ "$STATUS" -eq 1 ]; then
  if [ -f "$HOOK_PATH" ]; then
    printf "  ${G}installed${Z}: %s\n" "$HOOK_PATH"
    head -3 "$HOOK_PATH"
  else
    printf "  ${D}not installed${Z}: %s\n" "$HOOK_PATH"
  fi
  exit 0
fi

if [ "$UNINSTALL" -eq 1 ]; then
  if [ -f "$HOOK_PATH" ]; then
    rm -f "$HOOK_PATH"
    printf "  ${G}Removed${Z} %s\n" "$HOOK_PATH"
  else
    printf "  ${D}Nothing to remove${Z} (no hook at %s)\n" "$HOOK_PATH"
  fi
  exit 0
fi

if [ -f "$HOOK_PATH" ] && [ "$FORCE" -eq 0 ]; then
  echo "ERROR: $HOOK_PATH already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

mkdir -p "$(dirname "$HOOK_PATH")"

cat > "$HOOK_PATH" <<'HOOK'
#!/bin/bash
# AI News Briefing — pre-commit hook
# Generated by scripts/git-hooks-install.sh. Edit via that script.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if [ -t 1 ]; then
  G='\033[32m'; R='\033[31m'; Y='\033[33m'; D='\033[90m'; Z='\033[0m'
else
  G=''; R=''; Y=''; D=''; Z=''
fi

STAGED="$(git diff --cached --name-only --diff-filter=ACMR)"
[ -z "$STAGED" ] && exit 0

FAIL=0

# 1) bash -n on staged shell scripts
SH_FILES="$(echo "$STAGED" | grep -E '\.sh$' || true)"
if [ -n "$SH_FILES" ]; then
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    [ -f "$f" ] || continue
    if ! bash -n "$f" 2>/tmp/pre-commit.err.$$; then
      printf "  ${R}SYNTAX${Z} %s\n" "$f"
      sed 's/^/      /' </tmp/pre-commit.err.$$
      FAIL=1
    fi
    rm -f /tmp/pre-commit.err.$$
  done <<<"$SH_FILES"
fi

# 2) plugin-validate.sh if any plugin file is staged
if echo "$STAGED" | grep -qE '^(claude-plugins|plugins|gemini-extensions)/' \
   && [ -f scripts/plugin-validate.sh ]; then
  if ! bash scripts/plugin-validate.sh >/tmp/pre-commit.plug.$$ 2>&1; then
    printf "  ${R}plugin-validate.sh failed${Z}\n"
    tail -40 /tmp/pre-commit.plug.$$ | sed 's/^/      /'
    FAIL=1
  fi
  rm -f /tmp/pre-commit.plug.$$
fi

# 3) Portability tests (fast)
if [ -f tests/test-portability.sh ]; then
  if ! bash tests/test-portability.sh >/tmp/pre-commit.port.$$ 2>&1; then
    printf "  ${R}tests/test-portability.sh failed${Z}\n"
    tail -40 /tmp/pre-commit.port.$$ | sed 's/^/      /'
    FAIL=1
  fi
  rm -f /tmp/pre-commit.port.$$
fi

if [ "$FAIL" -ne 0 ]; then
  printf "\n  ${R}Pre-commit failed${Z}. Fix issues above or commit with ${D}--no-verify${Z}.\n\n"
  exit 1
fi

printf "  ${G}Pre-commit checks passed.${Z}\n"
HOOK

chmod +x "$HOOK_PATH"
printf "  ${G}Installed${Z} %s\n" "$HOOK_PATH"
printf "  ${D}Hook runs: bash -n on staged .sh, plugin-validate (if plugins changed), tests/test-portability.sh.${Z}\n"
printf "  ${D}Bypass with: git commit --no-verify${Z}\n"
